version: "3.9"

services:
  cardano-node:
    image: inputoutput/cardano-node:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./cardano-configurations/network/testnet:/config
      - ./testnet/node.db:/db
      - ./ipc:/ipc
    environment:
      - CARDANO_SOCKET_PATH=/ipc/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket # used by cardano-cli
    command:
      [ "run"
      , "--config", "/config/cardano-node/config.json"
      , "--topology", "/config/cardano-node/topology.json"
      , "--database-path", "/db"
      ]

  hydra-node:
    image: ghcr.io/input-output-hk/hydra-node:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - .:/credentials:ro
      - ./ipc:/ipc
      - ./genesis-shelley.json:/genesis-shelley.json
      - ./protocol-parameters.json:/protocol-parameters.json
    ports:
      - "4001:4001"
      - "5001:5001"
    command:
      [ "--node-id", "1"
      , "--api-host", "0.0.0.0"
      , "--host", "0.0.0.0"
      , "--monitoring-port", "6001"
      , "--hydra-signing-key", "/credentials/arnaud-hydra.sk"
      , "--cardano-signing-key", "/credentials/arnaud.sk"
      , "--ledger-genesis", "/genesis-shelley.json"
      , "--ledger-protocol-parameters", "/protocol-parameters.json"
      , "--network-id", "${NETWORK_MAGIC:-42}"
      , "--node-socket", "/ipc/node.socket"
      ]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  promtail:
    image: grafana/promtail:1.4.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
