version: "3.9"

services:
  cardano-node:
    image: inputoutput/cardano-node:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./devnet:/devnet
    environment:
      - CARDANO_SOCKET_PATH=/devnet/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/devnet/node.socket # used by cardano-cli
    command:
      [ "run"
      , "--config", "/devnet/cardano-node.json"
      , "--topology", "/devnet/topology.json"
      , "--database-path", "/devnet/db"
      ]


  hydra-node:
    image: ghcr.io/input-output-hk/hydra-node:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - .:/keys:ro
      - ./devnet:/devnet
    ports:
      - "4001:4001"
    command:
      [ "--node-id", "1"
      , "--api-host", "0.0.0.0"
      , "--host", "172.16.238.10"
      , "--monitoring-port", "6001"
      , "--hydra-scripts-tx-id", "${HYDRA_SCRIPTS_TX_ID}"
      , "--hydra-signing-key", "/keys/arnaud-hydra.sk"
      , "--cardano-signing-key", "/keys/arnaud.sk"
      , "--ledger-genesis", "/devnet/genesis-shelley.json"
      , "--ledger-protocol-parameters", "/devnet/protocol-parameters.json"
      , "--network-id", "${NETWORK_MAGIC}"
      , "--node-socket", "/devnet/node.socket"
      ]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  # promtail:
  #   image: grafana/promtail:1.4.1
  #   volumes:
  #     - /var/lib/docker/containers:/var/lib/docker/containers
  #     - ./promtail-config.yml:/etc/promtail/promtail-config.yml
  #   command: -config.file=/etc/promtail/promtail-config.yml
