name: Docker

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
    tags: [ "*.*.*" ]

jobs:
  docker:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        repository: [ hydra ]

    runs-on: ${{ matrix.os }}
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v2.3.3

    - name: 🧰 Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 🧐 hadolint
      uses: brpaz/hadolint-action@v1.5.0
      with:
        dockerfile: "./Dockerfile"
        failure-threshold: warning

    - name: 🐳 Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: 🔨 Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: inputoutput/${{ matrix.repository }}:latest
        cache-from: type=registry,ref=inputoutput/${{ matrix.repository }}:latest
        cache-to: type=inline

    - name: 📝 Variables
      if: ${{ startsWith(github.ref, 'refs/tags') }}
      id: variables
      run: |
        echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: 🏷️ Build and push (tag)
      if: ${{ startsWith(github.ref, 'refs/tags') }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: inputoutput/${{ matrix.repository }}:${{ steps.variables.outputs.tag }}
        cache-from: type=registry,ref=inputoutput/${{ matrix.repository }}:latest
        cache-to: type=inline
