# This workflow builds docker images on 'master', for all release tags, but also
# for all pull requests. It only tags and pushes all builds from 'master' and
# releases. However, the 'latest' docker tag on the registry will always point
# to the latest version (likely the one built from 'master') so referring to the
# versioned images is suggested.
name: Docker

on:
  push:
    branches: [ "master" ]
    tags: [ "*.*.*" ]
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    strategy:
      matrix:
        target: [ hydra-node, hydra-tui, hydra-tools, hydraw ]

    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: 🧰 Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 🐳 Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: ❄ Prepare nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          accept-flake-config = true

    - name: 📝 Prepare docker image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ matrix.target }}
        tags: |
          unstable
          type=semver,pattern={{version}}

    - name: 🔨 Build images using nix
      run: |
        nix build .#docker.${{ matrix.target }} && docker load < ./result
        # Create a dummy Dockerfile to not build, but tag & label in next step
        echo "FROM ${{matrix.target}}" > Dockerfile.dummy

    - name: 📤 Maybe push
      uses: docker/build-push-action@v3
      with:
        # Make sure to use the dummy docker file so we don't actually build
        context: .
        file: Dockerfile.dummy
        # Only push images from master or release tags, unless it's about
        # 'hydraw' (which is not yet versioned)
        push: ${{ github.ref == 'refs/heads/master' || (github.ref_type == 'tag' && matrix.target != 'hydraw') }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
