# This workflow builds docker images on 'master', for all release tags, but also
# for all pull requests. It only tags and pushes all builds from 'master' and
# releases. However, the 'latest' docker tag on the registry will always point
# to the latest version (likely the one built from 'master') so referring to the
# versioned images is suggested.
name: Docker

on:
  push:
    branches: [ "master" ]
    tags: [ "*.*.*" ]
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    strategy:
      matrix:
        target: [ hydra-node, hydra-tui, hydraw ]

    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v2.3.3
      with:
        submodules: true

    - name: 🧰 Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 🐳 Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 📝 Prepare docker image metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ matrix.target }}
        tags: |
          latest
          type=semver,pattern={{version}}

    - name: 🔨 Build and maybe push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        target: ${{ matrix.target }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
