name: Docker

on:
  push:
    branches: [ "master", "ch1bo/multiple-docker-images" ]
    tags: [ "*.*.*" ]

jobs:
  docker:
    strategy:
      matrix:
        target: [ hydra-node, hydra-tui ]

    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v2.3.3

    - name: 🧰 Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 🐳 Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 📝 Prepare docker image metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/{{ matrix.target }}
        tags: |
          latest
          type=semver,pattern={{version}}

    - name: 🔨 Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        target: ${{ matrix.target }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
