name: ManualTest

on:
  workflow_dispatch:

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        repository: input-output-hk/hydra-poc
        token: ${{ secrets.MY_TOKEN || github.token }}
        ref: feat/gh-pages/docs-custom-template/456

    - name: Documention metadata enrichment
      run: |
        DOCS_DIR="docs/*.md"
        DOCUMENTS=$(git ls-files $DOCS_DIR)

        for MD in $DOCUMENTS; do
            echo "updating: $MD"

            PLACEHOLDER="{{last-updated-at}}"
            REPLACEMENT=$(git --no-pager log -1 --pretty=format:'%ad' --date=local $MD)
            sed -i "s/$PLACEHOLDER/$REPLACEMENT/g" $MD

            PLACEHOLDER="{{relative-time-since}}"
            REPLACEMENT=$(git --no-pager log -1 --pretty=format:'%cr' $MD)
            sed -i "s/$PLACEHOLDER/$REPLACEMENT/g" $MD

            PLACEHOLDER="{{commit-hash}}"
            REPLACEMENT=$(git --no-pager log -1 --pretty=format:'%h' $MD)
            sed -i "s/$PLACEHOLDER/$REPLACEMENT/g" $MD

            PLACEHOLDER="{{last-translated-at}}"
            REPLACEMENT=$(git --no-pager log -1 --pretty=format:'%ad' --date=local docs/i18n)
            sed -i "s/$PLACEHOLDER/$REPLACEMENT/g" $MD

        done

