name: "Publish Docs"

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master, release]
    types: 
      - completed

jobs:
  publishing:
    name: Publish Documentation
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: 📥 Download last released docs
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci.yaml
        workflow_conclusion: success
        branch: release
        name: docs-stable
        path: docs-release

    - name: 📥 Download latest docs
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci.yaml
        workflow_conclusion: success
        branch: master
        name: docs-stable
        path: docs-master

    - name: 📥 Download latest /unstable docs
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci.yaml
        workflow_conclusion: success
        branch: master
        name: docs-unstable
        path: docs-master-unstable

    - name: 🪓 Piece together docs
      run: |
        mkdir public
        mv docs-release public/head-protocol
        mv docs-master-unstable public/head-protocol/unstable
        # Always use monthly reports from master
        # XXX: This depends on languages and assets are annoying
        rm -r public/head-protocol/monthly
        mv docs-master/monthly public/head-protocol/monthly
        rm -r public/head-protocol/ja/monthly
        mv docs-master/ja/monthly public/head-protocol/ja/monthly
        rm -r public/head-protocol/fr/monthly
        mv docs-master/fr/monthly public/head-protocol/fr/monthly
        # XXX: Need to copy assets as well. This will also litter with unrelated assets (js)
        cp -r docs-master/assets/* public/head-protocol/assets/
        cp -r docs-master/ja/assets/* public/head-protocol/ja/assets/
        cp -r docs-master/fr/assets/* public/head-protocol/fr/assets/

    - name: 👉 Create redirect
      run: |
        echo "hydra.family" > public/CNAME
        echo '<!DOCTYPE html><html><head><meta http-equiv="Refresh" content="0; URL=https://hydra.family/head-protocol"></head></html>' > public/index.html

    - name: 🚢 Publish Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN || github.token }}
        publish_dir: public
        enable_jekyll: true
        force_orphan: true
    
